# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: The Wordy Home of gogetdane
email: go@getdane.co.uk
description: Stuff I've discovered that other people may find useful!
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  gogetdane

# Build settings
#theme: minimal-mistakes-jekyll
remote_theme: "mmistakes/minimal-mistakes@4.24.0"
plugins:
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

defaults:
  - scope:
      path: ""
      type: posts
    values:
      author_profile: true
      layout: single
      classes: wide
      author:
        name     : "Dane Stevens"
        avatar   : "/assets/me.jpeg"
        bio      : |
          Senior Software Engineer & Solutions Architect
        location : "Worcestershire, UK"
        github_username: gogetdane
        links:
          - label: "LinkedIn"
            icon: "fab fa-fw fa-linkedin-in"
            url: "https://www.linkedin.com/in/danestevens/"
          - label: "GitHub"
            icon: "fab fa-fw fa-github"
            url: "https://github.com/gogetdane"
          - label: "Email"
            icon: "fas fa-fw fa-envelope-square"
            url: "mailto:go@getdane.co.uk"

  - scope:
      path: ""
      type: pages
    values:
      author_profile: true
      layout: single
      classes: wide
      author:
        name     : "Dane Stevens"
        avatar   : "/assets/me.jpeg"
        bio      : |
          Senior Software Engineer & Solutions Architect
        location : "Worcestershire, UK"
        github_username: gogetdane
        links:
          - label: "LinkedIn"
            icon: "fab fa-fw fa-linkedin-in"
            url: "https://www.linkedin.com/in/danestevens/"
          - label: "GitHub"
            icon: "fab fa-fw fa-github"
            url: "https://github.com/gogetdane"
          - label: "Email"
            icon: "fas fa-fw fa-envelope-square"
            url: "mailto:go@getdane.co.uk"


    
#minimal_mistakes_skin: "dark"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
